### ISSUE TITLE
Arc Browser Support

### ISSUE THREAD

**Issue by sheikheddy** [ActivityWatch/aw-watcher-web#122] opened 2024-03-12 14:32 UTC
Does aw-watcher-web support https://arc.net/?

**Comment by KakouMoses** [comment] 2024-04-16 21:23
I think it's not. It's actually detecting the data from the Chromium kernel inside of it, but not including them into the overall statistics on the browser.
It's seen in the timeline, but not in the Activity section.

**Comment by Chaoscontrol** [comment] 2024-07-14 07:59
Exactly this. It "works", but it just doesn't seem to be processed and recognised.

**Comment by johan-bjareholt** [comment] 2024-07-14 14:38
Duplicate of #118

**Closed by johan-bjareholt** 2024-07-14 14:38 UTC
