### ISSUE TITLE
Firefox Watcher does not maintain the host name

### ISSUE THREAD

**Issue by TrigonaMinima** [ActivityWatch/aw-watcher-web#48] opened 2020-04-22 19:37 UTC
The Firefox watcher doesn't maintain the `Hostname` in the `Raw Data` tab. So while exporting, the bucketname is same if the plugin is installed in 2 different systems. And while importing this gives errors on the other machine.

![image](https://user-images.githubusercontent.com/2520893/80025739-bc10d200-84fe-11ea-851d-dc6e91477935.png)

**Comment by ErikBjare** [comment] 2020-04-23 06:09
Duplicate of issue https://github.com/ActivityWatch/activitywatch/issues/307

In a future version this will be fixed and all pre-existing web buckets (with "unknown" hostname) will have their hostnames migrated to the host name of the server machine at that time (not ideal, but will work for most people who haven't done export/import of web buckets, the rest will have to manually rename).

**Closed by ErikBjare** 2020-04-23 06:09 UTC

**Comment by TrigonaMinima** [comment] 2020-04-23 06:40
Cool. Sorry didn't check the older issue.

**Comment by ErikBjare** [comment] 2020-04-23 08:40
No worries, your issue reminded me that it breaks export/import as well, so it was still of use :)
