### ISSUE TITLE
[WARNING]: Inserting event that has a older timestamp than previous event!

### ISSUE THREAD

**Issue by dufferzafar** [ActivityWatch/aw-watcher-web#16] opened 2018-03-17 18:43 UTC
I'm running ActivityWatch from source (latest master repo) and using the Firefox extension.

I keep getting these warnings in the log, why could they be occurring?

```
2018-03-17 23:28:42 [WARNING]: Inserting event that has a older timestamp than previous event!
Previous:{'id': 758, 'duration': datetime.timedelta(0), 'timestamp': datetime.datetime(2018, 3, 17, 17, 58, 41, 956000, tzinfo=datetime.timezone.utc), 'data': {'title': '[REDACTED]', 'incognito': False, 'url': '[REDACTED]', 'audible': False}}
Inserted:{'id': 759, 'duration': datetime.timedelta(0), 'timestamp': datetime.datetime(2018, 3, 17, 17, 58, 41, 955000, tzinfo=datetime.timezone.utc), 'data': {'title': '[REDACTED]', 'incognito': False, 'url': '[REDACTED]', 'audible': False}}  (aw_datastore.datastore.Bucket:113)
```

**Comment by johan-bjareholt** [comment] 2018-03-17 21:59
Hm, odd. It's clear that one event is exactly 1ms earlier than the other one but it is received before it, that should be a programming error.
Not sure how this occurs, will look into it.

**Comment by johan-bjareholt** [comment] 2018-03-17 22:03
This part is likely the cause

https://github.com/ActivityWatch/aw-watcher-web/blob/master/app/eventPage.js#L49
```
// Any tab data has changed, finish previous event and insert new event
else if (JSON.stringify(last_heartbeat_data) != JSON.stringify(data)){
  //console.log("aw-watcher-web: Change");
  client.sendHeartbeat(new Date(now-1), last_heartbeat_data, heartbeat_pulsetime);
  client.sendHeartbeat(now, data, heartbeat_pulsetime);
  last_heartbeat_data = data;
  last_heartbeat_time = now;
}
```

Both the closing event and the new event are sent in the right order, but since the requests are asyncronous there's no guarantee which one will be received first from aw-server.

**Comment by dufferzafar** [comment] 2018-03-18 03:34
Then perhaps we should expect this to happen and not throw up Warning
messages?

**Comment by johan-bjareholt** [comment] 2018-03-18 08:32
We do not want this to happen due to how heartbeats works, the order they are inserted is important. We should fix it in the watcher itself somehow, just have to figure out what's the best way to do it.

**Comment by Otto-AA** [comment] 2018-06-17 06:35
Implemented in https://github.com/ActivityWatch/aw-client-js/pull/7

**Comment by johan-bjareholt** [comment] 2018-06-20 16:17
Will be fixed by https://github.com/ActivityWatch/aw-watcher-web/pull/19

**Closed** 2020-03-29 16:24 UTC
Labels: bug
