### ISSUE TITLE
Firefox extension still not recording until toggled off and on again

### ISSUE THREAD

**Issue by Joeyrsp** [ActivityWatch/aw-watcher-web#108] opened 2023-05-15 07:21 UTC
extension: 0.4.7
firefox: 113.0.1 (64-bit)

When inspecting the extension the console has nothing.

I appreciate that there has been an attempt to address this issue already but it seems like the update that was pushed out hasn't fixed things.

**Comment by Aziks0** [comment] 2023-05-16 11:29
Duplicate of #107

**Closed** 2023-05-16 14:06 UTC
