### ISSUE TITLE
Notification about losing connection to server is really big and distracting

### ISSUE THREAD

**Issue by youve** [ActivityWatch/aw-watcher-web#31] opened 2019-03-29 05:53 UTC
I installed AW a few weeks ago and I really love it. The other day, I installed the browser extension for Firefox. Since then, periodically throughout the day, more than once an hour, I get a giant message that AW has either lost connection or resumed connection to the local server.

I would like to be able to turn this message off, or for it to be a lot smaller so that it doesn't get in the way of whatever I'm doing. I care a lot more about my concentration than about whether every second of my day is successfully tracked.

I'm attaching a screenshot:
![2019-03-29-062916_1280x1024_scrot](https://user-images.githubusercontent.com/25477622/55212206-32a1aa00-51ef-11e9-9b73-8aeed64e232f.png)

Thanks for your help

**Comment by youve** [comment] 2019-03-29 05:58
Oh I think I know why this is happening.

I'm using awesome as my window manager and I suspect the reason the message is so big is the AW icon; I'm guessing it uses lib-notify or something and doesn't provide sizing information for the image? Maybe there could be a 16 px x 16 px icon used in lib-notify events instead of the full sized image?

**Comment by johan-bjareholt** [comment] 2019-03-29 11:24
That notification comes from Firefox via the webextension api chrome.notifications.create, there is no option for us to set the size of the notification.
We are using a SVG as the icon so the image can scale indefinitely without any loss in quality and apparently this is the default behavior for your WM when getting a SVG as the notification icon.

https://github.com/ActivityWatch/aw-watcher-web/blob/master/src/client.js#L5

The issue is either with your WM or with Firefox, we cannot do anything about this unfortunately.

**Comment by johan-bjareholt** [comment] 2019-03-29 11:27
On the other hand, we'd love to know why aw-server is sometimes not responding. Can you send us your aw-server log?

**Comment by youve** [comment] 2019-03-29 11:54
That makes sense. Any chance of an option to disable notifications then?

By aw-server log, do you mean I should go to http://localhost:5600/#/buckets and export aw-watcher-web-firefox as json or something else?

Is there a term I could grep for you to avoid sending you the entire thing? It's 490KB and I do sometimes search google maps for locations near where I live, which is an example of something I'd like to redact.

**Comment by johan-bjareholt** [comment] 2019-03-29 12:17
Not the bucket data, the server log. On linux there's a log in ~/.cache/activitywatch/aw-server I believe.

**Comment by youve** [comment] 2019-03-29 12:27
Found it, thank you. ~/.cache/activitywatch/log/aw-server
[aw-server_2019-03-29T12-03-14.log](https://github.com/ActivityWatch/aw-watcher-web/files/3022597/aw-server_2019-03-29T12-03-14.log)

`2019-03-29 13:24:27 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-window_maths)  (aw_server.api:212)`

This line was added at the time that I got one of those pop up notifications

**Comment by johan-bjareholt** [comment] 2019-03-29 13:17
That message doesn't really indicate that something is wrong with aw-server, only that it possibly got the heartbeat a bit late. My guess is that your computer (CPU or HDD) is just a bit slow and the request times out. Our datastore is currently very unoptimized but we have a lot of optimizations about to land soon which should hopefully make this very rare even on slow computers.

If you want, you can try the new WIP datastore which should have better performance by going to "~/.config/activitywatch/aw-server/aw-server.ini" and change "storage = peewee" with "storage = sqlite".

**Comment by youve** [comment] 2019-03-29 13:43
Oh, that makes a lot of sense. My CPU is 1.86GHz but the real problem is that I only have 4GB of RAM, the maximum my aging motherboard supports. Lately it seems that running an IDE and a web browser at the same time is too much to ask of it. When I switch between programs, it can take a few seconds for it to realise i've started typing, so if AW is also trying to send a heartbeat then it's also not going to get processor time as soon as it expects.

ActivityWatch has been very polite with my system resources, at least. It is not using very much memory of CPU. 

I've changed to sqlite data storage now. Thanks for the suggestion.

**Comment by ErikBjare** [comment] 2019-03-29 14:31
@youve FWIW, I have the exact same issue with the icon sizing (I'm using i3 and Firefox). 

Also @johan-bjareholt, it seems we pass a PNG (not an SVG) as the `iconUrl` parameter when we create the notification, which would definitely explain the issue. A simple downscaling of the PNG should do the trick, there's probably guidelines for how large the icons should be somewhere.

**Comment by johan-bjareholt** [comment] 2019-03-29 17:56
The fact that the WM doesn't scale it at all is really the issue IMO. I now see though that Chrome doesn't support SVG icons at all for notifications so it makes sense that we don't use that. I guess that a 128px icon should be good enough for both HiDPI and standard dpi though (we currently use a 256px icon) so we should just switch to the existing logo-128.png icon in media. It's a sub-optimal solution, but a solution nonetheless.

I have firefox + an ancient version of i3 on my work computer (debian stable) but that old i3 version doesn't even seem to support icons in the notifications lol.

**Comment by johan-bjareholt** [comment] 2019-03-29 18:03
@youve ActivityWatch is not efficient but neither is it bloated IMO. While the peewee datastore doesn't use much CPU or RAM but it does continuous read/writes to your HDD/SSD which is bad. The SQLite datastore does less frequent writes to the database and writes in batches which should make performance especially better on HDDs.

We haven't had many testers for the sqlite datastore yet @youve, so please report if you have any issues or if it simply just works properly! The first time you set the datastore to sqlite it should also automatically migrate the data from the old datastore to the new one, did that work properly for you?

**Comment by youve** [comment] 2019-03-30 05:40
The change took effect automatically the next time I started the server. I can view my data from today and from previous days at http://localhost:5600/#/activity/maths. The messages in .xsession-errors look fine:

```
2019-03-30 05:45:40 [INFO ]: Starting module aw-server  (aw_qt.manager:46)
2019-03-30 05:45:40 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:46)
2019-03-30 05:45:40 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:46)
2019-03-30 05:45:40 [INFO ]: Creating trayicon...  (aw_qt.trayicon:150)
INFO:aw_server.main:Using storage method: sqlite
2019-03-30 05:45:46 [INFO ]: Using storage method: sqlite  (aw_server.main:26)
INFO:aw_server.main:Starting up...
2019-03-30 05:45:46 [INFO ]: Starting up...  (aw_server.main:31)
INFO:aw_datastore.storages.sqlite:Using database file: /home/after/.local/share/activitywatch/aw-server/sqlite.v1.db
2019-03-30 05:45:57 [INFO ]: Using database file: /home/after/.local/share/activitywatch/aw-server/sqlite.v1.db  (aw_datastore.storages.sqlite:69)
2019-03-30 05:45:58 [INFO ]: aw-watcher-afk started  (aw_watcher_afk.afk:53)
2019-03-30 05:45:58 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:42)
INFO:aw_datastore.storages.sqlite:Created new SQlite db file
2019-03-30 05:45:59 [INFO ]: Created new SQlite db file  (aw_datastore.storages.sqlite:81)
INFO:aw_datastore.migration:Migrating database from peewee v2 to sqlite v1
2019-03-30 05:45:59 [INFO ]: Migrating database from peewee v2 to sqlite v1  (aw_datastore.migration:31)
INFO:aw_datastore.storages.peewee:Using database file: /home/after/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db
2019-03-30 05:45:59 [INFO ]: Using database file: /home/after/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:90)
INFO:aw_datastore.migration:Migrating bucket aw-watcher-window_maths
2019-03-30 05:45:59 [INFO ]: Migrating bucket aw-watcher-window_maths  (aw_datastore.migration:38)
2019-03-30 05:45:59 [WARNING]: Not connected to server, 0 requests in queue  (aw_client.client:368)
2019-03-30 05:45:59 [WARNING]: Not connected to server, 0 requests in queue  (aw_client.client:368)
2019-03-30 05:46:01 [WARNING]: window_prop was None  (aw_watcher_window.xlib:23)
2019-03-30 05:46:02 [WARNING]: window_prop was None  (aw_watcher_window.xlib:23)
2019-03-30 05:46:03 [WARNING]: window_prop was None  (aw_watcher_window.xlib:23)
2019-03-30 05:46:04 [WARNING]: window_prop was None  (aw_watcher_window.xlib:23)
2019-03-30 05:46:05 [WARNING]: window_prop was None  (aw_watcher_window.xlib:23)
2019-03-30 05:46:06 [WARNING]: window_prop was None  (aw_watcher_window.xlib:23)
2019-03-30 05:46:07 [WARNING]: window_prop was None  (aw_watcher_window.xlib:23)
2019-03-30 05:46:29 [WARNING]: Not connected to server, 2 requests in queue  (aw_client.client:368)
2019-03-30 05:46:29 [WARNING]: Not connected to server, 4 requests in queue  (aw_client.client:368)
INFO:aw_datastore.migration:Migrating bucket aw-watcher-afk_maths
2019-03-30 05:46:34 [INFO ]: Migrating bucket aw-watcher-afk_maths  (aw_datastore.migration:38)
INFO:aw_datastore.migration:Migrating bucket aw-stopwatch
2019-03-30 05:46:35 [INFO ]: Migrating bucket aw-stopwatch  (aw_datastore.migration:38)
INFO:aw_datastore.migration:Migrating bucket aw-watcher-web-firefox
2019-03-30 05:46:35 [INFO ]: Migrating bucket aw-watcher-web-firefox  (aw_datastore.migration:38)
INFO:aw_datastore.migration:Migration of peewee v2 to sqlite v1 finished
2019-03-30 05:46:37 [INFO ]: Migration of peewee v2 to sqlite v1 finished  (aw_datastore.migration:50)
INFO:werkzeug: * Running on http://localhost:5600/ (Press CTRL+C to quit)
2019-03-30 05:46:37 [INFO ]:  * Running on http://localhost:5600/ (Press CTRL+C to quit)  (werkzeug:88)
2019-03-30 05:46:39 [INFO ]: Connection to aw-server established by aw-watcher-afk  (aw_client.client:336)
INFO:aw_server.api:Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-afk_maths)
2019-03-30 05:46:39 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-afk_maths)  (aw_server.api:212)
2019-03-30 05:46:39 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:336)
```

By the way, I think `2019-03-30 05:46:02 [WARNING]: window_prop was None  (aw_watcher_window.xlib:23)` happens when I switch to a desktop with nothing running (except the root window which displays my background image), which I usually do when I go afk to prevent the cat from messing anything up.

**Comment by johan-bjareholt** [comment] 2019-03-30 07:34
@youve Oh, that looks really nice. Thanks for reporting!

> By the way, I think 2019-03-30 05:46:02 [WARNING]: window_prop was None (aw_watcher_window.xlib:23) happens when I switch to a desktop with nothing running (except the root window which displays my background image), which I usually do when I go afk to prevent the cat from messing anything up.

Correct, that log message should probably be lowered to a INFO instead of WARNING.

**Comment by ErikBjare** [comment] 2019-05-03 17:59
The oversized notification icon was fixed in: https://github.com/ActivityWatch/aw-watcher-web/pull/34

**Closed by ErikBjare** 2019-05-03 17:59 UTC
